### ISSUE TITLE
Output is empty and source is becomes empty after process

### ISSUE THREAD

**Issue by toros1969** [ndjc/controlfreak#1]
Hi Nick Crossley,

I tested with 
OpenJDK21U-jdk_x64_windows_hotspot_21.0.5_11.msi

java -jar controlfreak.jar -o CMC850.FA1 -t CMC850.txt

Am I missing something?
Do you have a newer version available that works?

Could you please send a .bat converting the sample files?
Thanks,

Olivier

**Comment by ndjc** [comment]
You provided two output files (one binary and one text), but you did not provide any input files. For that reason, both output files were created or overwritten to be empty.

You need to provide at least one input file, as an argument with no option/flag:
java -jar controlfreak.jar -o CMC850.FA1 -t CMC850.txt MyPrograms.txt

If you provide more than one input file, those input files are merged into the output or outputs:

java -jar controlfreak.jar -o CMC850.FA1 -t CMC850.txt MyExtraProgs.txt MyPreviousData.FA1

I admit the silent empty output with no input arguments is counter-intuitive - I’ll fix that to show an error message.

Nick.

**Comment by ndjc** [comment]
Fixed in 578bd5d
